on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: flask web app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ vars.HOST }}
        username: ${{ vars.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          pwd
          chmod +x deploy_production.sh
          echo $GITHUB_ACTION_PATH
          bash deploy_production.sh
